/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface PaymentLedgerInterface extends Interface {
    getFunction(nameOrSignature: "logPayment"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PaymentLogged"): EventFragment;

    encodeFunctionData(functionFragment: 'logPayment', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'logPayment', data: BytesLike): Result;
  }

  
    export namespace PaymentLoggedEvent {
      export type InputTuple = [paymentHash: BytesLike, timestamp: BigNumberish];
      export type OutputTuple = [paymentHash: string, timestamp: bigint];
      export interface OutputObject {paymentHash: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PaymentLedger extends BaseContract {
    
    connect(runner?: ContractRunner | null): PaymentLedger;
    waitForDeployment(): Promise<this>;

    interface: PaymentLedgerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    logPayment: TypedContractMethod<
      [paymentHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'logPayment'): TypedContractMethod<
      [paymentHash: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'PaymentLogged'): TypedContractEvent<PaymentLoggedEvent.InputTuple, PaymentLoggedEvent.OutputTuple, PaymentLoggedEvent.OutputObject>;

    filters: {
      
      'PaymentLogged(bytes32,uint256)': TypedContractEvent<PaymentLoggedEvent.InputTuple, PaymentLoggedEvent.OutputTuple, PaymentLoggedEvent.OutputObject>;
      PaymentLogged: TypedContractEvent<PaymentLoggedEvent.InputTuple, PaymentLoggedEvent.OutputTuple, PaymentLoggedEvent.OutputObject>;
    
    };
  }