# Generated by Django 6.0.6 on 2026-07-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ocr_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
