# Generated by Django 6.0.6 on 2026-07-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_streak',
            field=models.IntegerField(default=0),
        ),
    ]
