/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { PaymentLedger, PaymentLedgerInterface } from "../PaymentLedger.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "paymentHash",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "PaymentLogged",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "paymentHash",
        "type": "bytes32"
      }
    ],
    "name": "logPayment",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234801561001057600080fd5b50610159806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063fb92c84c14610030575b600080fd5b61004a600480360381019061004591906100c2565b61004c565b005b807f140bc6de7544424e03a814df12a1f33cb119ef7a164102535d4fdbb3e69ea83e4260405161007c9190610108565b60405180910390a250565b600080fd5b6000819050919050565b61009f8161008c565b81146100aa57600080fd5b50565b6000813590506100bc81610096565b92915050565b6000602082840312156100d8576100d7610087565b5b60006100e6848285016100ad565b91505092915050565b6000819050919050565b610102816100ef565b82525050565b600060208201905061011d60008301846100f9565b9291505056fea264697066735822122009eeeac035b543c273bfef53cfdb442a6c826e0538073ba1fc64f3a579c90e6564736f6c63430008130033";

  
      type PaymentLedgerConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: PaymentLedgerConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class PaymentLedger__factory extends ContractFactory {
    
      constructor(...args: PaymentLedgerConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<PaymentLedger & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): PaymentLedger__factory {
      return super.connect(runner) as PaymentLedger__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): PaymentLedgerInterface {
      return new Interface(_abi) as PaymentLedgerInterface;
    }
    
    override attach(address: string | Addressable): PaymentLedger {
      return super.attach(address) as PaymentLedger;
    }
  static connect(address: string, runner?: ContractRunner | null): PaymentLedger {
      return new Contract(address, _abi, runner) as unknown as PaymentLedger;
    }
  }

  
  